id: PDB6F8F49
initial_creation_type: input
source_metadata:
  title: Acala Series
  language: bo
  description: 'Texts related to Acala (mi g.yo ba), the ‘Immovable One’, a wrathful
    deity who is also known as Caṇḍamahāroṣaṇa:'
  volume:
    82a18c75f8a04d4db9b1aa80cecd97f9:
      title: Acala Sādhana
      parent: Sādhanas
created_at: '2022-03-01T02:29:53.995429'
last_modified_at: '2022-03-01T02:29:53.995432'
